version: "3"
services:
  news-homepage:
    container_name: news-homepage
    build:
     context: .
     dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app